# Copyright (c) 2016-2021 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Databend
site_url: https://databend.rs
site_author: DatafuseLabs
site_description: >-
  Built to make the Data Cloud easy.

# Repository
repo_name: datafuselabs/databend
repo_url: https://github.com/datafuselabs/databend
edit_uri: "https://github.com/datafuselabs/databend/tree/main/website/databend/docs"

# Copyright
copyright: Copyright &copy; 2020 - 2021 Datafuse Labs

# Configuration
theme:
  name: null
  custom_dir: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datafuselabs

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Documentation:
      - Overview:
          - Installation: overview/building-and-running.md
      - SQL Reference:
          - Data Types:
              - Integer Numbers: sqlstatement/data-types/data-type-integer-number.md
              - Real Numbers: sqlstatement/data-types/data-type-real-number.md
              - String Types: sqlstatement/data-types/data-type-string-types.md
              - Time and Date: sqlstatement/data-types/data-type-time-date-types.md
          - Data Definition Language:
              - CREATE DATABASE: sqlstatement/data-definition-language-ddl/ddl-create-database.md
              - DROP DATABASE: sqlstatement/data-definition-language-ddl/ddl-drop-database.md
              - CREATE TABLE: sqlstatement/data-definition-language-ddl/ddl-create-table.md
              - DROP TABLE: sqlstatement/data-definition-language-ddl/ddl-drop-table.md
              - TRUNCATE TABLE: sqlstatement/data-definition-language-ddl/ddl-truncate-table.md
          - Data Manipulation Language:
              - SELECT: sqlstatement/data-manipulation-language-dml/dml-select.md
              - INSERT: sqlstatement/data-manipulation-language-dml/dml-insert.md
          - Describe Commands:
              - DESCRIBE TABLE: sqlstatement/describe-commands/describe-table.md
          - Show Commands:
              - SHOW CREATE TABLE: sqlstatement/show-commands/show-create-table.md
              - SHOW DATABASES: sqlstatement/show-commands/show-databases.md
              - SHOW PROCESSLIST: sqlstatement/show-commands/show-processlist.md
              - SHOW TABLES: sqlstatement/show-commands/show-tables.md
              - SHOW SETTINGS: sqlstatement/show-commands/show-settings.md
              - SHOW METRICS: sqlstatement/show-commands/show-metrics.md
              - SHOW USERS: sqlstatement/show-commands/show-users.md
          - Kill Commands:
              - KILL QUERY: sqlstatement/kill-commands/kill-query.md
          - Aggregate Functions:
              - AVG: sqlstatement/aggregate-functions/aggregate-avg.md
              - COUNT: sqlstatement/aggregate-functions/aggregate-count.md
              - MIN: sqlstatement/aggregate-functions/aggregate-min.md
              - MAX: sqlstatement/aggregate-functions/aggregate-max.md
              - SUM: sqlstatement/aggregate-functions/aggregate-sum.md
              - DISTINCT: sqlstatement/aggregate-functions/aggregate-combinator.md
              - argMin: sqlstatement/aggregate-functions/aggregate-argmin.md
              - argMax: sqlstatement/aggregate-functions/aggregate-argmax.md
              - avgIf: sqlstatement/aggregate-functions/aggregate-avg-if.md
              - countIf: sqlstatement/aggregate-functions/aggregate-count-if.md
              - minIf: sqlstatement/aggregate-functions/aggregate-min-if.md
              - maxIf: sqlstatement/aggregate-functions/aggregate-max-if.md
              - sumIf: sqlstatement/aggregate-functions/aggregate-sum-if.md
              - STDDEV_POP: sqlstatement/aggregate-functions/aggregate-stddev-pop.md
              - COVAR_SAMP: sqlstatement/aggregate-functions/aggregate-covar-samp.md
              - windowFunnel: sqlstatement/aggregate-functions/aggregate-windowfunnel.md
          - Conditional Functions:
              - IF: sqlstatement/conditional-functions/if.md
          - Conversion Functions:
              - CAST: sqlstatement/conversion-functions/cast.md
              - Type Conversion: sqlstatement/conversion-functions/type-conversion.md
          - Date and Time Functions:
              - NOW: sqlstatement/datetime-functions/now.md
              - TODAY: sqlstatement/datetime-functions/today.md
              - TOMORROW: sqlstatement/datetime-functions/tomorrow.md
              - toYYYYMM: sqlstatement/datetime-functions/toyyyymm.md
              - toYYYYMMDD: sqlstatement/datetime-functions/toyyyymmdd.md
              - toYYYYMMDDhhmmss: sqlstatement/datetime-functions/toyyyymmddhhmmss.md
              - toStartOfYear: sqlstatement/datetime-functions/tostartofyear.md
              - toStartOfISOYear: sqlstatement/datetime-functions/tostartofisoyear.md
              - YESTERDAY: sqlstatement/datetime-functions/yesterday.md
              - addYEARS/MONTHS/DAYS/HOURS/MINUTES/SECONDS: sqlstatement/datetime-functions/addinterval.md
              - subtractYEARS/MONTHS/DAYS/HOURS/MINUTES/SECONDS: sqlstatement/datetime-functions/subtractinterval.md
          - Hash Functions:
              - SIPHASH: sqlstatement/hash-functions/siphash.md
          - Information Functions:
              - DATABASE: sqlstatement/information-functions/database.md
              - VERSION: sqlstatement/information-functions/version.md
          - Nullable Functions:
              - isNull: sqlstatement/nullable-functions/isnull.md
              - isNotNull: sqlstatement/nullable-functions/isnotnull.md
          - Numeric Functions:
              - PI: sqlstatement/numeric-functions/pi.md
              - SIN: sqlstatement/numeric-functions/sin.md
              - COS: sqlstatement/numeric-functions/cos.md
              - TAN: sqlstatement/numeric-functions/tan.md
              - COT: sqlstatement/numeric-functions/cot.md
              - CRC32: sqlstatement/numeric-functions/crc32.md
              - DEGREES: sqlstatement/numeric-functions/degrees.md
              - RADIANS: sqlstatement/numeric-functions/radians.md
          - String Functions:
              - SUBSTRING: sqlstatement/string-functions/substring.md
          - Test Functions:
              - SLEEP: sqlstatement/test-functions/sleep.md
              - CRASHME: sqlstatement/test-functions/crashme.md
          - Other Functions:
              - ToTypeName: sqlstatement/other-functions/totypename.md
              - runningDifference: sqlstatement/other-functions/running-difference.md
          - System Tables: system/system-tables.md
          - User Management:
              - CREATE USER: sqlstatement/user-management/user-management-create-user.md
      - API:
          - Config: api/config.md
  - CLI: cli/cli.md
  - Development:
      - Contributing: development/contributing.md
      - Coding Guideline: development/coding-guidelines.md
      - Tracing: development/tracing.md
      - Profling: development/profiling.md
      - Roadmap: development/roadmap.md
      - Databend release channels: development/release-channels.md
      - How to write aggregate functions: development/how-to-write-aggregate-functions.md
      - How to get server logs: development/how-to-get-server-logs.md
      - RFCs:
          - DatabendQuery Join: rfcs/query/0001-join-framework-design.md
          - DatabendQuery Expression: rfcs/query/0002-plan-expression.md
          - DatabendQuery Shuffle: rfcs/query/0003-data-shuffle.md
          - Performance Test: rfcs/query/0004-performance-test.md
          - SQL Planner Framework: rfcs/query/0005-new-sql-planner-framework.md
          - DatabendCLI Design: rfcs/cli/0001-cli-design.md
  - Performance: overview/performance.md
  - Whitepapers: overview/architecture.md
  - Weekly: https://datafuselabs.github.io/weekly/

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
